CREATE TABLE [dbo].[BaiDang]
(
	[ID] NCHAR(50) NOT NULL PRIMARY KEY, 
    [IDUser] NVARCHAR(50) NULL, 
    [TieuDe] NVARCHAR(50) NULL, 
    [KhuVuc] NVARCHAR(50) NULL, 
    [MoTa] NVARCHAR(MAX) NULL, 
    [Date] DATETIME2 NULL, 
    [KinhNghiem] NVARCHAR(50) NULL, 
    [GhiChu] NVARCHAR(MAX) NULL
)


Insert into BaiDang Values ('1', '1', N'Cần thuê thợ điện tử chuyên nghiệp cho dự án mới', N'Thủ Đức', N'Đảm bảo sửa chữa và bảo trì các thiết bị điện tử trong dự án mới, bao gồm máy tính, máy in, thiết bị điện tử khác theo yêu cầu', N'2024-3-4', N'1 - 2 năm', N'Có kinh nghiệm trong việc sửa chữa và bảo trì thiết bị điện tử, hiểu biết về các linh kiện điện tử, có khả năng xử lý sự cố.', N'Ưu tiên ứng viên có bằng cấp và chứng chỉ liên quan đến điện tử.')
Insert into BaiDang Values ('2', '2', N'Tìm kiếm thợ điện lạnh có kinh nghiệm tại khu vực đô thị mới', N'Quận 1', N'Thực hiện việc sửa chữa, lắp đặt và bảo dưỡng hệ thống điều hòa không khí, tủ lạnh và các thiết bị điện lạnh khác.', N'2024-3-4', N'1 - 2 năm', N'Có kinh nghiệm ít nhất 2 năm trong lĩnh vực điện lạnh, hiểu biết vững về các loại máy lạnh và tủ lạnh, có khả năng làm việc độc lập và theo nhóm.' ,N'Ưu tiên ứng viên có khả năng giao tiếp tốt và thái độ chuyên nghiệp.')
Insert into BaiDang Values ('3', '3', N'Gấp! Tuyển dụng thợ sửa máy tính tại nhà', N'Quận 2', N'Đi đến nhà khách hàng để kiểm tra, sửa chữa và cài đặt phần mềm cho máy tính cá nhân hoặc văn phòng.', N'2024-3-4', N'1 - 2 năm', N'Có kiến thức chuyên sâu về phần cứng và phần mềm máy tính, khả năng phát hiện và khắc phục sự cố nhanh chóng.', N'Đề xuất tính phí dịch vụ trước khi bắt đầu công việc và tuân thủ chính sách giá của công ty.')
Insert into BaiDang Values ('4', '4', N'Cần thợ gia sư dạy kèm môn Toán lớp 10', N'Quận 3', N'Dạy kèm môn Toán cho học sinh lớp 10, giúp họ hiểu và áp dụng các kiến thức Toán học một cách hiệu quả.', N'2024-3-4', N'1 - 2 năm', N'Hiểu biết sâu rộng về chương trình Toán lớp 10, khả năng truyền đạt thông tin một cách dễ hiểu và phương pháp giảng dạy linh hoạt.', N'Ưu tiên ứng viên có kinh nghiệm làm gia sư và có kiến thức vững chắc về Toán.')
Insert into BaiDang Values ('5', '5', N'Tìm thợ sửa nhà uy tín để cải thiện không gian sống', N'Quận 4', N'Thực hiện các công việc sửa chữa và nâng cấp nhà cửa, bao gồm sơn sửa, lắp đặt và cải thiện không gian sống.', N'2024-3-4', N'1 - 2 năm', N'Kỹ năng làm việc chuyên nghiệp, hiểu biết về các quy trình sửa chữa nhà cửa, có khả năng làm việc theo yêu cầu của khách hàng.', N'Ưu tiên ứng viên có kinh nghiệm làm việc trong ngành xây dựng và sửa nhà.')
Insert into BaiDang Values ('6', '6', N'Cần thuê thợ điện nước lành nghề cho công trình xây dựng', N'Quận 5', N'Thực hiện các công việc liên quan đến hệ thống điện và nước trong công trình xây dựng, bao gồm lắp đặt, bảo trì và sửa chữa.', N'2024-3-4', N'1 - 2 năm', N'Yêu cầu có thái độ chuyên nghiệp và cẩn thận trong công việc, có trách nhiệm, hiểu biết về các vấn đề kỹ thuật và có khả năng xử lý tình huống một cách nhanh chóng.', N'Ưu tiên ứng viên có bằng cấp hoặc chứng chỉ liên quan đến điện nước và có kinh nghiệm làm việc trong ngành xây dựng.')
Insert into BaiDang Values ('7', '7', N'Gấp! Tìm thợ bảo trì máy móc cho nhà máy sản xuất', N'Quận 7', N'Thực hiện bảo trì, sửa chữa và duy trì các thiết bị và máy móc trong nhà máy sản xuất để đảm bảo hoạt động suôn sẻ và an toàn.', N'2024-3-4', N'1 - 2 năm', N'Kỹ năng làm việc chuyên nghiệp, hiểu biết vững về các hệ thống điện và nước, có kinh nghiệm làm việc trong môi trường xây dựng.', N'Ưu tiên ứng viên có kinh nghiệm làm việc trong môi trường sản xuất và hiểu biết về các quy trình bảo trì máy móc.')
Insert into BaiDang Values ('8', '8', N'Cần tuyển thợ sửa máy giặt tại gia', N'Bình Thạnh', N'Cung cấp dịch vụ sửa chữa, bảo dưỡng và lắp đặt máy giặt tại nhà cho các hộ gia đình và khách hàng cá nhân.', N'2024-3-4', N'1 - 2 năm', N'Kỹ năng sửa chữa máy giặt, hiểu biết về cấu tạo và hoạt động của các loại máy giặt, có khả năng di chuyển linh hoạt và làm việc tại nhà khách hàng.', N'Ưu tiên ứng viên có kinh nghiệm làm việc trong lĩnh vực sửa chữa thiết bị gia đình.')
Insert into BaiDang Values ('9', '9', N'Tìm kiếm thợ điện tử sửa chữa điện thoại di động', N'Quận 8', N'Thực hiện sửa chữa, thay thế linh kiện và nâng cấp phần mềm cho điện thoại di động của khách hàng.', N'2024-3-4', N'1 - 2 năm', N'Kỹ năng sửa chữa điện thoại di động, hiểu biết về các dòng điện thoại và hệ điều hành di động, có khả năng làm việc chính xác và cẩn thận.', N'Ưu tiên ứng viên có kinh nghiệm làm việc trong ngành sửa chữa điện thoại di động và có khả năng giải quyết các vấn đề kỹ thuật phức tạp.')
Insert into BaiDang Values ('10', '10', N'Cần thợ điện lạnh để lắp đặt hệ thống điều hòa mới', N'Quận 9', N'Lắp đặt và cài đặt các hệ thống điều hòa không khí mới cho các căn hộ, nhà ở và văn phòng.', N'2024-3-4', N'1 - 2 năm', N'Kỹ năng lắp đặt điều hòa không khí, hiểu biết về các loại máy điều hòa và hệ thống làm lạnh, có khả năng làm việc theo yêu cầu của khách hàng.', N'Ưu tiên ứng viên có kinh nghiệm trong việc lắp đặt và bảo trì hệ thống điều hòa không khí.')


Insert into BaiDang Values ('11', '1', N'Gấp! Cần thuê gia sư môn Văn lớp 12', N'Thủ Đức', N'Đảm bảo sửa chữa và bảo trì các thiết bị điện tử trong dự án mới, bao gồm máy tính, máy in, thiết bị điện tử khác theo yêu cầu', N'2024-3-4', N'1 - 2 năm', N'Có kinh nghiệm trong việc sửa chữa và bảo trì thiết bị điện tử, hiểu biết về các linh kiện điện tử, có khả năng xử lý sự cố.', N'Ưu tiên ứng viên có bằng cấp và chứng chỉ liên quan đến điện tử.')
Insert into BaiDang Values ('12', '2', N'Tìm kiếm thợ điện lạnh có kinh nghiệm tại khu vực đô thị mới', N'Quận 1', N'Thực hiện việc sửa chữa, lắp đặt và bảo dưỡng hệ thống điều hòa không khí, tủ lạnh và các thiết bị điện lạnh khác.', N'2024-3-4', N'1 - 2 năm', N'Có kinh nghiệm ít nhất 2 năm trong lĩnh vực điện lạnh, hiểu biết vững về các loại máy lạnh và tủ lạnh, có khả năng làm việc độc lập và theo nhóm.' ,N'Ưu tiên ứng viên có khả năng giao tiếp tốt và thái độ chuyên nghiệp.')
Insert into BaiDang Values ('13', '3', N'Gấp! Tuyển dụng thợ sửa máy tính tại nhà', N'Quận 2', N'Đi đến nhà khách hàng để kiểm tra, sửa chữa và cài đặt phần mềm cho máy tính cá nhân hoặc văn phòng.', N'2024-3-4', N'1 - 2 năm', N'Có kiến thức chuyên sâu về phần cứng và phần mềm máy tính, khả năng phát hiện và khắc phục sự cố nhanh chóng.', N'Đề xuất tính phí dịch vụ trước khi bắt đầu công việc và tuân thủ chính sách giá của công ty.')
Insert into BaiDang Values ('14', '4', N'Cần thợ gia sư dạy kèm môn Toán lớp 10', N'Quận 3', N'Dạy kèm môn Toán cho học sinh lớp 10, giúp họ hiểu và áp dụng các kiến thức Toán học một cách hiệu quả.', N'2024-3-4', N'1 - 2 năm', N'Hiểu biết sâu rộng về chương trình Toán lớp 10, khả năng truyền đạt thông tin một cách dễ hiểu và phương pháp giảng dạy linh hoạt.', N'Ưu tiên ứng viên có kinh nghiệm làm gia sư và có kiến thức vững chắc về Toán.')
Insert into BaiDang Values ('15', '5', N'Tìm thợ sửa nhà uy tín để cải thiện không gian sống', N'Quận 4', N'Thực hiện các công việc sửa chữa và nâng cấp nhà cửa, bao gồm sơn sửa, lắp đặt và cải thiện không gian sống.', N'2024-3-4', N'1 - 2 năm', N'Kỹ năng làm việc chuyên nghiệp, hiểu biết về các quy trình sửa chữa nhà cửa, có khả năng làm việc theo yêu cầu của khách hàng.', N'Ưu tiên ứng viên có kinh nghiệm làm việc trong ngành xây dựng và sửa nhà.')
Insert into BaiDang Values ('16', '6', N'Cần thuê thợ điện nước lành nghề cho công trình xây dựng', N'Quận 5', N'Thực hiện các công việc liên quan đến hệ thống điện và nước trong công trình xây dựng, bao gồm lắp đặt, bảo trì và sửa chữa.', N'2024-3-4', N'1 - 2 năm', N'Yêu cầu có thái độ chuyên nghiệp và cẩn thận trong công việc, có trách nhiệm, hiểu biết về các vấn đề kỹ thuật và có khả năng xử lý tình huống một cách nhanh chóng.', N'Ưu tiên ứng viên có bằng cấp hoặc chứng chỉ liên quan đến điện nước và có kinh nghiệm làm việc trong ngành xây dựng.')
Insert into BaiDang Values ('17', '7', N'Gấp! Tìm thợ bảo trì máy móc cho nhà máy sản xuất', N'Quận 7', N'Thực hiện bảo trì, sửa chữa và duy trì các thiết bị và máy móc trong nhà máy sản xuất để đảm bảo hoạt động suôn sẻ và an toàn.', N'2024-3-4', N'1 - 2 năm', N'Kỹ năng làm việc chuyên nghiệp, hiểu biết vững về các hệ thống điện và nước, có kinh nghiệm làm việc trong môi trường xây dựng.', N'Ưu tiên ứng viên có kinh nghiệm làm việc trong môi trường sản xuất và hiểu biết về các quy trình bảo trì máy móc.')
Insert into BaiDang Values ('18', '8', N'Cần tuyển thợ sửa máy giặt tại gia', N'Bình Thạnh', N'Cung cấp dịch vụ sửa chữa, bảo dưỡng và lắp đặt máy giặt tại nhà cho các hộ gia đình và khách hàng cá nhân.', N'2024-3-4', N'1 - 2 năm', N'Kỹ năng sửa chữa máy giặt, hiểu biết về cấu tạo và hoạt động của các loại máy giặt, có khả năng di chuyển linh hoạt và làm việc tại nhà khách hàng.', N'Ưu tiên ứng viên có kinh nghiệm làm việc trong lĩnh vực sửa chữa thiết bị gia đình.')
Insert into BaiDang Values ('19', '9', N'Tìm kiếm thợ điện tử sửa chữa điện thoại di động', N'Quận 8', N'Thực hiện sửa chữa, thay thế linh kiện và nâng cấp phần mềm cho điện thoại di động của khách hàng.', N'2024-3-4', N'1 - 2 năm', N'Kỹ năng sửa chữa điện thoại di động, hiểu biết về các dòng điện thoại và hệ điều hành di động, có khả năng làm việc chính xác và cẩn thận.', N'Ưu tiên ứng viên có kinh nghiệm làm việc trong ngành sửa chữa điện thoại di động và có khả năng giải quyết các vấn đề kỹ thuật phức tạp.')
Insert into BaiDang Values ('20', '10', N'Cần thợ điện lạnh để lắp đặt hệ thống điều hòa mới', N'Quận 9', N'Lắp đặt và cài đặt các hệ thống điều hòa không khí mới cho các căn hộ, nhà ở và văn phòng.', N'2024-3-4', N'1 - 2 năm', N'Kỹ năng lắp đặt điều hòa không khí, hiểu biết về các loại máy điều hòa và hệ thống làm lạnh, có khả năng làm việc theo yêu cầu của khách hàng.', N'Ưu tiên ứng viên có kinh nghiệm trong việc lắp đặt và bảo trì hệ thống điều hòa không khí.')
