CREATE TABLE [dbo].[BaiDang]
(
	[ID] NCHAR(50) NOT NULL PRIMARY KEY, 
    [IDUser] NVARCHAR(50) NULL, 
    [TieuDe] NVARCHAR(50) NULL, 
    [KhuVuc] NVARCHAR(50) NULL, 
    [MoTa] NVARCHAR(MAX) NULL, 
    [Date] DATETIME2 NULL, 
    [KinhNghiem] NVARCHAR(50) NULL, 
    [GhiChu] NVARCHAR(MAX) NULL
)

Insert into BaiDang Values ('1', '1', N'Tìm thợ sửa máy lạnh tại gia', N'Thủ Đức', N'Đang tìm kiếm một thợ sửa máy lạnh uy tín và chuyên nghiệp để làm việc tại nhà. Vui lòng liên hệ nếu bạn có kinh nghiệm và sẵn lòng đảm bảo cho hệ thống máy lạnh hoạt động tốt.', N'2024-3-4', N'1 - 2 năm', N'Yêu cầu có thái độ chuyên nghiệp và cẩn thận trong công việc, có trách nhiệm, hiểu biết về các vấn đề kỹ thuật và có khả năng xử lý tình huống một cách nhanh chóng.')
Insert into BaiDang Values ('2', '2', N'Tìm thợ sơn tường biệt thự', N'Quận 1', N'Đang tìm kiếm một thợ sửa máy lạnh uy tín và chuyên nghiệp để làm việc tại nhà. Vui lòng liên hệ nếu bạn có kinh nghiệm và sẵn lòng đảm bảo cho hệ thống máy lạnh hoạt động tốt.', N'2024-3-4', N'1 - 2 năm', N'Yêu cầu có thái độ chuyên nghiệp và cẩn thận trong công việc, có trách nhiệm, hiểu biết về các vấn đề kỹ thuật và có khả năng xử lý tình huống một cách nhanh chóng.')
Insert into BaiDang Values ('3', '3', N'Tìm thợ sửa đường ống nước', N'Quận 2', N'Đang tìm kiếm một thợ sửa máy lạnh uy tín và chuyên nghiệp để làm việc tại nhà. Vui lòng liên hệ nếu bạn có kinh nghiệm và sẵn lòng đảm bảo cho hệ thống máy lạnh hoạt động tốt.', N'2024-3-4', N'1 - 2 năm', N'Yêu cầu có thái độ chuyên nghiệp và cẩn thận trong công việc, có trách nhiệm, hiểu biết về các vấn đề kỹ thuật và có khả năng xử lý tình huống một cách nhanh chóng.')
Insert into BaiDang Values ('4', '4', N'Tìm gia sư dạy kèm cấp 2', N'Quận 3', N'Đang tìm kiếm một thợ sửa máy lạnh uy tín và chuyên nghiệp để làm việc tại nhà. Vui lòng liên hệ nếu bạn có kinh nghiệm và sẵn lòng đảm bảo cho hệ thống máy lạnh hoạt động tốt.', N'2024-3-4', N'1 - 2 năm', N'Yêu cầu có thái độ chuyên nghiệp và cẩn thận trong công việc, có trách nhiệm, hiểu biết về các vấn đề kỹ thuật và có khả năng xử lý tình huống một cách nhanh chóng.')
Insert into BaiDang Values ('5', '5', N'Tìm thợ sửa tivi cao cấp', N'Quận 4', N'Đang tìm kiếm một thợ sửa máy lạnh uy tín và chuyên nghiệp để làm việc tại nhà. Vui lòng liên hệ nếu bạn có kinh nghiệm và sẵn lòng đảm bảo cho hệ thống máy lạnh hoạt động tốt.', N'2024-3-4', N'1 - 2 năm', N'Yêu cầu có thái độ chuyên nghiệp và cẩn thận trong công việc, có trách nhiệm, hiểu biết về các vấn đề kỹ thuật và có khả năng xử lý tình huống một cách nhanh chóng.')
Insert into BaiDang Values ('6', '6', N'Tìm thợ sửa tủ lạnh', N'Quận 5', N'Đang tìm kiếm một thợ sửa máy lạnh uy tín và chuyên nghiệp để làm việc tại nhà. Vui lòng liên hệ nếu bạn có kinh nghiệm và sẵn lòng đảm bảo cho hệ thống máy lạnh hoạt động tốt.', N'2024-3-4', N'1 - 2 năm', N'Yêu cầu có thái độ chuyên nghiệp và cẩn thận trong công việc, có trách nhiệm, hiểu biết về các vấn đề kỹ thuật và có khả năng xử lý tình huống một cách nhanh chóng.')
Insert into BaiDang Values ('7', '7', N'Tìm thợ sửa máy giặt', N'Quận 7', N'Đang tìm kiếm một thợ sửa máy lạnh uy tín và chuyên nghiệp để làm việc tại nhà. Vui lòng liên hệ nếu bạn có kinh nghiệm và sẵn lòng đảm bảo cho hệ thống máy lạnh hoạt động tốt.', N'2024-3-4', N'1 - 2 năm', N'Yêu cầu có thái độ chuyên nghiệp và cẩn thận trong công việc, có trách nhiệm, hiểu biết về các vấn đề kỹ thuật và có khả năng xử lý tình huống một cách nhanh chóng.')
Insert into BaiDang Values ('8', '8', N'Tìm thợ sửa máy vi tính', N'Bình Thạnh', N'Đang tìm kiếm một thợ sửa máy lạnh uy tín và chuyên nghiệp để làm việc tại nhà. Vui lòng liên hệ nếu bạn có kinh nghiệm và sẵn lòng đảm bảo cho hệ thống máy lạnh hoạt động tốt.', N'2024-3-4', N'1 - 2 năm', N'Yêu cầu có thái độ chuyên nghiệp và cẩn thận trong công việc, có trách nhiệm, hiểu biết về các vấn đề kỹ thuật và có khả năng xử lý tình huống một cách nhanh chóng.')
Insert into BaiDang Values ('9', '9', N'Tìm thợ sửa loa công suất lơn', N'Quận 8', N'Đang tìm kiếm một thợ sửa máy lạnh uy tín và chuyên nghiệp để làm việc tại nhà. Vui lòng liên hệ nếu bạn có kinh nghiệm và sẵn lòng đảm bảo cho hệ thống máy lạnh hoạt động tốt.', N'2024-3-4', N'1 - 2 năm', N'Yêu cầu có thái độ chuyên nghiệp và cẩn thận trong công việc, có trách nhiệm, hiểu biết về các vấn đề kỹ thuật và có khả năng xử lý tình huống một cách nhanh chóng.')
Insert into BaiDang Values ('10', '10', N'Tìm thợ sửa đường điện', N'Quận 9', N'Đang tìm kiếm một thợ sửa máy lạnh uy tín và chuyên nghiệp để làm việc tại nhà. Vui lòng liên hệ nếu bạn có kinh nghiệm và sẵn lòng đảm bảo cho hệ thống máy lạnh hoạt động tốt.', N'2024-3-4', N'1 - 2 năm', N'Yêu cầu có thái độ chuyên nghiệp và cẩn thận trong công việc, có trách nhiệm, hiểu biết về các vấn đề kỹ thuật và có khả năng xử lý tình huống một cách nhanh chóng.')
